name: Format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Java 11 setup
      - name: Java 11 setup
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'jetbrains'

      - name: Spotless
        run: mvn spotless:apply

      - name: Google Java Format
        uses: axel-op/googlejavaformat-action@v4.0.0
        with:
          args: --replace --skip-javadoc-formatting --skip-sorting-imports --skip-reflowing-long-strings
